- hosts: local
  tasks:
    - user:
          name: vnc_user
          state: present
    - package: 
          name: tigervnc
          state: present
    - copy:
          src: /lib/systemd/system/vncserver@.service
          dest: /etc/systemd/system/vncserver@:5.service
    - replace:
          path: /etc/systemd/system/vncserver@:5.service
          regexp: <USER>
          replace: vnc_user
    - service:
          name: firewalld
          state: stopped
